Add openssl thread synchronization to fix crashes
ibmruntimes/openj9-openjdk-jdk14 pull request #34
Opened 2020-03-25 18:32 UTC by shanchao95

Openssl 1.0.2 is not safely used in multi-thread application.
The change adds threadid and locking callback functions to provide
thread-safety when openssl 1.0.2 is used. It fixes issue 8373,
test crash in openjdk, jdk_net_0,
com/sun/net/httpserver/Test9a.java

Signed-off-by: Chao Shan <chao.shan@ibm.com>

2020-03-25 18:32 UTC, shanchao95 commented
@keithc-ca Code updated

2020-04-01 15:22 UTC, shanchao95 commented
@keithc-ca Code updated

2020-04-01 17:33 UTC, keithc-ca requested changes
Please also add the missing space after `if` on line 1312.

2020-04-01 17:33 UTC, keithc-ca commented on closed/src/java.base/share/native/libjncrypto/NativeCrypto.c
> +# define CRYPTO_LOCK 1
Please remove the space before `define`.

2020-04-01 17:33 UTC, keithc-ca commented on closed/src/java.base/share/native/libjncrypto/NativeCrypto.c
> +            if (thread_setup() != 0) {
Please put the constant on the left.

2020-04-01 18:28 UTC, shanchao95 commented
@keithc-ca Sorry for missing the parts, both jdk14 and jdk next code updated.

2020-04-01 18:37 UTC, keithc-ca commented
> Please also add the missing space after `if` on line 1312.

Can you address that too, please (here and in jdknext)?

2020-04-01 19:11 UTC, shanchao95 commented
> > Please also add the missing space after `if` on line 1312.
> 
> Can you address that too, please (here and in jdknext)?

Sure, code updated

2020-04-01 19:28 UTC, keithc-ca commented
Jenkins compile win,xlinux jdk14

2020-04-01 20:19 UTC, keithc-ca commented
Please fix the build error:
```
16:02:29  /home/jenkins/workspace/Build_JDK14_x86-64_linux_Personal/closed/src/java.base/share/native/libjncrypto/NativeCrypto.c:116:13: error: 'win32_locking_callback' declared 'static' but never defined [-Werror=unused-function]
16:02:29   static void win32_locking_callback(int mode, int type, const char *file, int line);
16:02:29               ^~~~~~~~~~~~~~~~~~~~~~
16:02:29  cc1: all warnings being treated as errors
```
You'll need to make conditionally declare platform-specific functions.

2020-04-01 20:27 UTC, keithc-ca commented
The build-error fixes should probably be applied to all jdk versions.

2020-04-06 15:58 UTC, keithc-ca commented
Jenkins compile win,xlinux jdk14

2020-04-06 19:40 UTC, keithc-ca commented
https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-OpenJDK14/17 should still be valid.

2020-04-06 19:40 UTC, keithc-ca approved these changes

2020-04-06 21:48 UTC, merged