Move message about checking for freemarker
ibmruntimes/openj9-openjdk-jdk14 pull request #47
Opened 2020-04-21 19:22 UTC by dnakamura

Move the message to inside the conditional where we actually check for
freemarker. Currently if  cmake is enabled, a message about checking
for freemarker is emitted, but no check is performed, and no response
emitted.

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

2020-04-24 12:40 UTC, keithc-ca requested changes

2020-04-24 12:40 UTC, keithc-ca commented on closed/autoconf/custom-hook.m4
> +    AC_MSG_CHECKING([that freemarker location is set])
I think the placement of this message is better in jdk8; please update accordingly.

2020-04-24 12:49 UTC, keithc-ca approved these changes

2020-04-24 12:50 UTC, keithc-ca commented
jdk15 needs the same fix. @dnakamura, will you address that too, please?

2020-04-27 20:03 UTC, keithc-ca commented
ping @dnakamura

2020-04-28 01:33 UTC, dnakamura commented
Oops. thoguht I already opened that one. Done 
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/195

2020-04-28 01:45 UTC, merged